# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "388b7f4cca66b74eb9d078a1fc558dcb"
name = "mailgun-api"
application_url = "https://test.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://test.com/api/auth" ]
